lab2: lab2.tex
	@latexmk -f -pdf -output-directory=build -shell-escape ./lab2.tex

lab3: lab3.tex
	@latexmk -f -pdf -output-directory=build -shell-escape ./lab3.tex

lab4: lab4.tex
	@latexmk -f -pdf -output-directory=build -shell-escape ./lab4.tex

lab5: lab5.tex
	@latexmk -f -pdf -output-directory=build -shell-escape ./lab5.tex
